export const USER_LOGIN = "USER_LOGIN";
export const USER_REGISTER = "USER_REGISTER";
//ADMIN
//-User
export const GET_USERLIST = "GET_USERLIST";
export const USER_UPDATE_ADMIN = "USER_UPDATE_ADMIN";
export const USER_DELETE = "USER_DELETE";
export const USER_SEARCHING = "USER_SEARCHING";
export const USER_EDIT = "USER_EDIT";
export const USER_ADD = "USER_ADD";

//-Course
export const GET_COURSELIST = "GET_COURSELIST";
export const DELETE_COURSE = "DELETE_COURSE";
export const EDITING_COURSE = "EDITING_COURSE";
export const UPDATE_COURSE_ADMIN = "UPDATE_COURSE_ADMIN";
export const ADD_NEW_COURSE = "ADD_NEW_COURSE";
export const GET_SEARCHING_LIST = "GET_SEARCHING_LIST";
export const GET_COURSE_STUDENT_LIST = "GET_COURSE_STUDENT_LIST";
export const GET_COURSE_INFO = "GET_COURSE_INFO";
export const CANCEL_REGISTER_COURSE = "CANCEL_REGISTER_COURSE";

export const GET_COURSE_CATAGORY = "GET_COURSE_CATAGORY";
